apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # This is an example base64 encoded Docker config.json for GitHub Container Registry
  # In production, create with:
  # kubectl create secret docker-registry ghcr-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=YOUR_GITHUB_USERNAME \
  #   --docker-password=YOUR_GITHUB_TOKEN \
  #   --docker-email=YOUR_EMAIL
  #
  # The value below is just a placeholder. DO NOT use in production.
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiWU9VUl9HSVRIVUJfVVNFUk5BTUUiLCJwYXNzd29yZCI6IllPVVJfR0lUSFVCX1RPS0VOIiwiZW1haWwiOiJZT1VSX0VNQUlMIiwiYXV0aCI6ImVYVmhjazlmWjJsMGFIVmlYM1Z6WlhKdVlXMWxPbVY0ZFhKZloyaDB"fX19